---
author:
title: "EDAV Fall 2019 PSet 5, part A"
output: pdf_document

---
```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)
```

This assignment is designed to help you get started on the final project. Be sure to review the final project instructions (https://edav.info/project.html), in particular the new section on reproducible workflow (https://edav.info/project.html#reproducible-workflow), which summarizes principles that we've discussed in class.
    
### 1. The Team

[2 points]

a) Who's on the team? (Include names and UNIs)
Yitao Liu (yl4343), Boyu Liu(bl2788), Yiyang Sun(ys3284)

b) How do you plan to divide up the work? (Grading is on a group basis. The point of asking is to encourage you to think about this.)
First of all, we want to do the data preprocessing first together. 
Then we will split the work by exploring at different aspects of the data (spatial, quantative). 



### 2. The Questions

[6 points]

List three questions that you hope you will be able to answer from your research.

a) With time going, how voilence pattern changes in all regions.

b) What's the difference for conflict patterns in different regions.

c) Whether thers is correlation between number of deaths and time or region. 

### 3. Which output format do you plan to use to submit the project? 

[2 points]

We choose html_document as the output format.


(Remember that it's ok to have pieces of the project that don't fit into the chosen output format; in those cases you can provide links to the relevant material.)

### 4. The Data

What is your data source?  What is your method for importing data? Please be specific. Provide relevant information such as any obstacles you're encountering and what you plan to do to overcome them.

[5 points]

UCDP Georeferenced Event Dataset (GED) Global version 19.1 from UCDP Dataset (https://ucdp.uu.se/downloads/index.html#ged_global)
The dataset has a RData version which we can directly load using R, so we don't have any  obstacle. 

### 5. Provide a short summary, including 2-3 graphs, of your initial investigations. 

[10 points]
